name: Arduino CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        fqbn:
          - arduino:avr:nano
          - arduino:avr:uno
    steps:
      - uses: actions/checkout@v3

      - name: Install Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh -s -- -b "$HOME/bin"
          echo "$HOME/bin" >> "$GITHUB_PATH"
          arduino-cli version

      - name: Install AVR core
        run: |
          command -v arduino-cli
          arduino-cli version
          arduino-cli core update-index
          arduino-cli core install arduino:avr

      - name: Compile sketch
        env:
          FQBN: ${{ matrix.fqbn }}
        run: ./ci/compile-sketch.sh
