name: Docs Check

on:
  pull_request:

jobs:
  markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Auto-fix Markdown
        run: |
          npx markdownlint-cli2 --fix "**/*.md"
          git diff --exit-code
